"""
tools/gen_prototypes.py — generate per-class mean spectrogram prototypes
as a C array for on-device MSE diagnostics.

Usage
-----
    python tools/gen_prototypes.py \
        --features data/processed/fsc22_melspec_val_32mel \
        --classes  Fire Thunderstorm Silence VehicleEngine Chainsaw \
                   Handsaw Gunshot WoodChop Speaking BirdChirping \
        --out-dir  deploy/nicla_cnn_10_classes-16x64-32mel

Writes:
    <out-dir>/src/prototypes.c
    <out-dir>/include/prototypes.h
"""

import argparse
import json
import numpy as np
from pathlib import Path


def compute_prototypes(features_dir: Path, class_filter: list[str]):
    features   = np.load(features_dir / "features.npy")   # (N, H, W)
    labels_int = np.load(features_dir / "labels.npy")
    label_names = json.load(open(features_dir / "label_names.json"))

    n_mels, n_frames = features.shape[1], features.shape[2]
    prototypes = []
    counts = []
    for cls in class_filter:
        if cls not in label_names:
            raise ValueError(f"Class '{cls}' not found. Available: {label_names}")
        idx  = label_names.index(cls)
        mask = labels_int == idx
        subs = features[mask]
        counts.append(len(subs))
        prototypes.append(subs.mean(axis=0))  # (n_mels, n_frames)

    return np.array(prototypes), class_filter, counts, n_mels, n_frames


def write_c(prototypes, class_names, counts, out_dir: Path):
    n_classes, n_mels, n_frames = prototypes.shape
    out_dir.mkdir(parents=True, exist_ok=True)
    src_dir = out_dir / "src"
    inc_dir = out_dir / "include"
    src_dir.mkdir(exist_ok=True)
    inc_dir.mkdir(exist_ok=True)

    # Quantize to uint8: values are in [0,1] after normalization → *255, round
    # This reduces flash from n*4 bytes to n*1 byte (4× smaller).
    # On-device MSE: dequantize with /255.0f before computing difference.
    proto_u8 = np.clip(np.round(prototypes * 255.0), 0, 255).astype(np.uint8)

    flash_kb = n_classes * n_mels * n_frames / 1024
    print(f"  Quantized to uint8: {flash_kb:.1f} KB flash "
          f"(was {flash_kb*4:.1f} KB as float32)")

    # ── header ────────────────────────────────────────────────────────────────
    h = f"""\
/* prototypes.h — per-class mean mel spectrogram prototypes (uint8, values 0-255 = [0,1])
   Auto-generated by tools/gen_prototypes.py — do not edit. */
#pragma once
#include <stdint.h>

#define PROTO_N_CLASSES  {n_classes}
#define PROTO_N_MELS     {n_mels}
#define PROTO_N_FRAMES   {n_frames}
#define PROTO_DIM        (PROTO_N_MELS * PROTO_N_FRAMES)

/* prototypes[class][mel * PROTO_N_FRAMES + frame], uint8, dequantize with /255.0f */
extern const uint8_t prototypes[PROTO_N_CLASSES][PROTO_DIM];
extern const char *proto_labels[PROTO_N_CLASSES];
"""
    (inc_dir / "prototypes.h").write_text(h)

    # ── source ────────────────────────────────────────────────────────────────
    lines = [
        "/* prototypes.c — auto-generated by tools/gen_prototypes.py */",
        '#include "prototypes.h"',
        "",
        f"/* {n_classes} classes × {n_mels} mels × {n_frames} frames "
        f"= {n_classes * n_mels * n_frames} bytes "
        f"({flash_kb:.1f} KB flash, uint8 quantized) */",
        "",
        "const char *proto_labels[PROTO_N_CLASSES] = {",
        "    " + ", ".join(f'"{c}"' for c in class_names),
        "};",
        "",
        "const uint8_t prototypes[PROTO_N_CLASSES][PROTO_DIM] = {",
    ]
    for ci, (cls, count) in enumerate(zip(class_names, counts)):
        flat = proto_u8[ci].flatten()
        lines.append(f"    /* [{ci}] {cls}  (n={count} samples) */")
        lines.append("    {")
        for start in range(0, len(flat), 16):
            chunk = flat[start:start+16]
            row = "        " + ", ".join(str(v) for v in chunk) + ","
            lines.append(row)
        lines.append("    },")
    lines.append("};")
    lines.append("")

    (src_dir / "prototypes.c").write_text("\n".join(lines))

    total_kb = n_classes * n_mels * n_frames * 4 / 1024
    print(f"Written {inc_dir}/prototypes.h and {src_dir}/prototypes.c")
    print(f"  {n_classes} classes × {n_mels}×{n_frames} = {total_kb:.1f} KB flash")
    for cls, count in zip(class_names, counts):
        print(f"  {cls}: {count} samples averaged")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--features", required=True,
                    help="Path to processed feature set directory")
    ap.add_argument("--classes", nargs="+", required=True,
                    help="Ordered list of class names matching model output order")
    ap.add_argument("--out-dir", required=True,
                    help="PlatformIO project root (src/ and include/ written here)")
    args = ap.parse_args()

    features_dir = Path(args.features)
    out_dir      = Path(args.out_dir)

    prototypes, class_names, counts, n_mels, n_frames = compute_prototypes(
        features_dir, args.classes
    )
    write_c(prototypes, class_names, counts, out_dir)


if __name__ == "__main__":
    main()
